spring.application.name=APIGateway
server.port=8081

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.enabled=true

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# ------------------------
# CORS (React -> Gateway)
# ------------------------
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# ---------------------------------------------------
# ROUTES (lb://SERVICE-NAME)  => LOAD BALANCED ROUTING
# ---------------------------------------------------

spring.cloud.gateway.routes[99].id=debug-catchall
spring.cloud.gateway.routes[99].uri=lb://INVESTOR-SERVICE
spring.cloud.gateway.routes[99].predicates[0]=Path=/api/**
spring.cloud.gateway.routes[99].filters[0]=StripPrefix=1

# Investor Service
spring.cloud.gateway.routes[0].id=Investor-Service
spring.cloud.gateway.routes[0].uri=lb://INVESTOR-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/investors/**

# Portfolio Service
spring.cloud.gateway.routes[1].id=Portfolio-Service
spring.cloud.gateway.routes[1].uri=lb://PORTFOLIO-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/portfolios/**

# Risk Score Service
spring.cloud.gateway.routes[2].id=Risk-Score-Service
spring.cloud.gateway.routes[2].uri=lb://RISK-SCORE-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/risk-scores/**

# Exposure Alert Service
spring.cloud.gateway.routes[3].id=Exposure-Alert-Service
spring.cloud.gateway.routes[3].uri=lb://EXPOSURE-ALERT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/alerts/**

# Compliance Report Service
spring.cloud.gateway.routes[4].id=Compliance-Service
spring.cloud.gateway.routes[4].uri=lb://COMPLIANCE-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/compliance/**

# Admin User Service
spring.cloud.gateway.routes[5].id=Admin-User-Service
spring.cloud.gateway.routes[5].uri=lb://ADMIN-USER-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/internal/**

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG
logging.level.com.netflix.discovery=INFO
